### ISSUE TITLE
StatefulSet?

### ISSUE THREAD

**Issue by billimek** [MoJo2600/pihole-kubernetes#19]
Currently, the chart deploys pihole as a [Deployment](https://github.com/MoJo2600/pihole-kubernetes/blob/master/pihole/templates/deployment.yaml).  After experimentation, I determined that it isn't a good idea to run more than one replica of pihole due to the shared nature of the storage used by multiple instances.

In cases where someone wants a more highly-available pihole workload (i.e. more than one instance running), I wonder if leveraging StatefulSet could help.  See [this primer](https://medium.com/stakater/k8s-deployments-vs-statefulsets-vs-daemonsets-60582f0c62d4) for a comparison between the different types.

Running pihole as a StatefulSet would mean the following:

* It would still be possible to run just one instance if desired
* When running more than one instance, each 'instance' would have a distinct copy of the filesystem that pihole uses.  This means that query log collection, settings, etc would all be separated from each instance and if you are hitting the service or ingress for pihole, you may see different results depending on which stateful instance happens to serve the request
* It should, in theory, allow for running multiple instances of pihole for a more highly-available deployment

Thoughts?

**Comment by MoJo2600** [comment]
What issues did you have with a shared database file. Sqlite should support multiple users connecting to the same file - but i never tried this.
Otherwise from my experience with kubernetes and statefulsets your are absolutely right. A Stateful Set would make sense here. Every pod has its own storage. The only downside i see is, that you don't have a single source of truth, when you are dependent on the query logs. For example when a page is blocked, i open the query log to see which url it is and add it to the whitelist. With the Loadbalancing in place, i think the request would be evenly distributed to all containers running and thus return randomly one of the containers (round robin). Or am i wrong with this?

Sorry for the late reply... been to the afk for a couple of weeks

**Comment by runningman84** [comment]
From my point of view it would be good if pihole would just output the logs to stdout and you query them via elasticsearch or something like that. In this case the sql lite database of pihole can be purged at will and changes to white or blacklist ips would be done using helm/gitops. I doubt that anybody would like to use the webinterface to do any change because you would have to go to each pod and configure everything multiple times.

**Comment by MoJo2600** [comment]
Yes, i see your point. The only thing that i currently use the web interface for is to see what is being blocked and to find urls that have to be whitelisted. But the whitelisting is all done via helm. As nice as elasticsearch is, it uses a lot of resources. I'm not sure if this is justified.

**Comment by billimek** [comment]
Having done more experimentation, I'd like to add additional thoughts/observations:

For the scenario by which one wants to achieve redundancy & high availability with pihole:

## statefulset

* Running multiple replicas guarantees that a single service will be exposed for all clients to consume (most likely a LoadBalancerIP in the case of pihole)
* Running multiple replicas guarantees that each instance of the pihole will have separate/isolated independent storage and no issues with multiple writes to the same database
* It is difficult to manage each instance configuration, and requires some port-forwarding of each pod to access each instance directly

## deployment

* It is not advisable to run multiple replicas of the same release of pihole using a deployment because of the same shared underlying storage
* It is, however, possible to run multiple different releases of pihole (e.g. a single replica named `pihole-a`, another single replica named `pihole-b`, and so on)
* In the case of multiple different releases, each 'release' will have their own separate/isolated independent storage and no issues with multiple writes to the same database
* In the case of multiple different releases, each 'release' will have it's own access path (i.e. some loadbalancer IP for `pihole-a` and a different loadbalancer IP for `pihole-b`) - this requires the DNS clients to be configured to know about multiple different pihole instances
* This scenario probably closely matches running multiple different piholes on multiple different devices
* Configuring each pihole instance is done by accessing each pihole's unique IP

## conclusion?

Is it 'better' to have a single IP address associated with DNS for pihole access (**statefulset** approach), or multiple different IP addresses (DNS) for multiple different piholes (**multiple deployment releases** approach)?

What do you all think?

**Comment by carpenike** [comment]
In the case of a dns client (at least for Windows), the client will round robin select a DNS server if it has more than one defined and will not failover your another until a timeout is reached. The client will not “blacklist” a downed DNS server either. Therefore having more than one IP, while functionally provides a highly available configuration, would end up with delays in DNS resolution on the client side for each unavailable DNS server attempted 

The correct approach IMO is to have a single DNS server assigned to clients with multiple endpoints behind a LB.

**Comment by runningman84** [comment]
BTW. I would recommend to checkout blocky. This project does not need persistent storage and can be configured using a simple yaml file. It has about the same features as pihole and works great in my k3s cluster. 

https://github.com/0xERR0R/blocky

**Comment by onedr0p** [comment]
The monolith of dependences pihole relies upon is crazy, blocky looks great. There's also Adguard Home which is also written in Go and is single binary.

https://github.com/AdguardTeam/AdGuardHome

**Comment by onedr0p** [comment]
@runningman84 is there a helm chart for blocky available, I'd love to try this out.

**Comment by billimek** [comment]
FYI, I just published a quick-and-dirty helm chart for blocky: https://github.com/billimek/billimek-charts/tree/master/charts/blocky

**Comment by MoJo2600** [comment]
I'm reopening this ticket. Pihole 5 moved from single files to a gravity database. So we need to move the deployment to a stateful set to support this database.

**Comment by MoJo2600** [comment]
I had a detailed look into pihole5 but I'm not sure if there is something that we would have to change. PiHole 5 introduced a gravity database. When the pod starts it reads in all files we currently define and imports them to the gravity database. If we would convert it to a StatefulSet every pod would have it's own PVC and thus it's own database. That is fine, until you change something, because this will only be persisted on the one instance you were working on. I think this is not what we want. Maybe we should stick to the Deployment with one PVC and use for everything else blocky, as already mentioned.

**Comment by MoJo2600** [comment]
I will close this. With persistence enabled pihole5 works really well.
